# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: node_js
node_js:
  - '8'
install: 
  - npm install
script: 
  - npm start 
notifications:
        email:
                recipients:
                - mathiass12@hotmail.com
                        on_success: always
                        on_failure: always

